services:
  - type: web
    name: phishcatcher
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn phishcatcher.wsgi:application
