# Generated by Django 5.1.7 on 2025-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('result', models.CharField(max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
