# Generated by Django 5.1.7 on 2025-05-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='features_triggered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='result',
            field=models.CharField(max_length=100),
        ),
    ]
